version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dio
      MONGO_INITDB_ROOT_PASSWORD: dio
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dio
      ME_CONFIG_MONGODB_ADMINPASSWORD: dio
      ME_CONFIG_MONGODB_URL: mongodb://dio:dio@mongo:27017/

  dashboard:
    build: .
    ports:
      - 8501:8501

volumes:
  mongo_data:
